services:
  primary_server:
    build:
      context: ../backend
    image: server
    container_name: primary_server
    ports:
      - "8887:8887"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 18.207.202.107:9092
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer"
      -Dexec.args="8887 5001 44.203.203.158:6001, 18.204.230.185:7001, 3.86.91.77:4001 true 44.206.0.115:9999"