version: '3.8'

services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_LOG_RETENTION_HOURS: "1"
      KAFKA_LOG_CLEANUP_POLICY: "delete"
    networks:
      mynetwork:
        ipv4_address: 172.16.238.10

  primary_server:
    image: server
    container_name: primary_server
    hostname: primary_server
    ports:
      - "8887:8887"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8887 5001 backup_server_1:6001,backup_server_2:7001,backup_server_3:4001 true"
    depends_on:
      - backup_server_1
      - backup_server_2
      - backup_server_3
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.11

  backup_server_1:
    build:
      context: ./backend
    image: server
    container_name: backup_server_1
    hostname: backup_server_1
    ports:
      - "8888:8888"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8888 6001 primary_server:5001,backup_server_2:7001,backup_server_3:4001 false"
    depends_on:
      - kafka
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.12

  backup_server_2:
    build:
      context: ./backend
    image: server
    container_name: backup_server_2
    hostname: backup_server_2
    ports:
      - "8889:8889"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8889 7001 primary_server:5001,backup_server_1:6001,backup_server_3:4001 false"
    depends_on:
      - kafka
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.13

  backup_server_3:
    build:
      context: ./backend
    image: server
    container_name: backup_server_3
    hostname: backup_server_3
    ports:
      - "8890:8890"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8890 4001 primary_server:5001,backup_server_1:6001,backup_server_2:7001 false"
    depends_on:
      - kafka
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.14

  connection_coordinator:
    build:
      context: ./backend
    image: connection_coordinator
    container_name: connection_coordinator
    hostname: connection_coordinator
    ports:
      - "9999:9999"
    command: >
      mvn exec:java -Dexec.mainClass="com.server.ConnectionCoordinator"
    networks:
      mynetwork:
        ipv4_address: 172.16.238.15

  client_1:
    build:
      context: ./frontend
    image: client
    container_name: client_1
    ports:
      - "3000:3000"
    depends_on:
      - primary_server
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.16

  client_2:
    image: client
    container_name: client_2
    ports:
      - "3001:3000"
    depends_on:
      - primary_server
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.17

  client_3:
    image: client
    container_name: client_3
    ports:
      - "3002:3000"
    depends_on:
      - primary_server
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.18

  client_4:
    image: client
    container_name: client_4
    ports:
      - "3003:3000"
    depends_on:
      - primary_server
      - connection_coordinator
    networks:
      mynetwork:
        ipv4_address: 172.16.238.19

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
