networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  kafka:
    networks:
        my_network:
          ipv4_address: 172.20.0.9
    image: apache/kafka:latest # Official Confluent Kafka image
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # Add this line
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      # Retention policy settings
      KAFKA_LOG_RETENTION_HOURS: "1"  # i Hour
      KAFKA_LOG_CLEANUP_POLICY: "delete"  # Delete old messages based on retention settings
    # volumes:
    #   - ./log4j.properties:/opt/kafka/config/log4j.properties  # Mount custom log4j.properties
  
  primary_server:
    networks:
      my_network:
        ipv4_address: 172.20.0.10
    image: server
    container_name: primary_server
    hostname: primary_server
    ports:
      - "8887:8887" # Expose port 8887 for client communication
      - "5001:5001" # Expose port 5001 for heartbeat communication
      - "5002:5002" # Expose port 5002 for Incremental Updates (otherServerHBPort + 1)
      - "5003:5003" # Expose port 5003 for Full game state updates (otherServerHBPort + 2)
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8887 5001 backup_server_1:6001,backup_server_2:7001,backup_server_3:4001 true"
    depends_on:
      - backup_server_1 # Guarantee startup order.
      - backup_server_2
      - backup_server_3
      - connection_coordinator
  
  backup_server_1:
    networks:
      my_network:
        ipv4_address: 172.20.0.11
    build:
      context: ./backend
    image: server
    container_name: backup_server_1
    hostname: backup_server_1
    ports:
      - "8888:8888" # Expose port 8888 for client communication
      - "6001:6001" # Expose port 6001 for heartbeat communication
      - "6002:6002" # Expose port 6002 for Incremental Updates (otherServerHBPort + 1)
      - "6003:6003" # Expose port 6003 for Full game state updates (otherServerHBPort + 2)
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8888 6001 primary_server:5001,backup_server_2:7001,backup_server_3:4001 false"
    depends_on:
      - kafka
      - connection_coordinator

  backup_server_2:
    networks:
        my_network:
          ipv4_address: 172.20.0.12
    build:
      context: ./backend
    image: server
    container_name: backup_server_2
    hostname: backup_server_2
    ports:
      - "8889:8889" # Expose port 8889 for client communication
      - "7001:7001" # Expose port 7001 for heartbeat communication
      - "7002:7002" # Expose port 7002 for Incremental Updates (otherServerHBPort + 1)
      - "7003:7003" # Expose port 7003 for Full game state updates (otherServerHBPort + 2)
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8889 7001 primary_server:5001,backup_server_1:6001,backup_server_3:4001 false"
    depends_on:
      - kafka
      - connection_coordinator
  
  backup_server_3:
    networks:
      my_network:
        ipv4_address: 172.20.0.13
    build:
      context: ./backend
    image: server
    container_name: backup_server_3
    hostname: backup_server_3
    ports:
      - "8890:8890" # Expose port 8890 for client communication
      - "4001:4001" # Expose port 4001 for heartbeat communication
      - "4002:4002" # Expose port 4002 for Incremental Updates (otherServerHBPort + 1)
      - "4003:4003" # Expose port 4003 for Full game state updates (otherServerHBPort + 2)
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8890 4001 primary_server:5001,backup_server_1:6001,backup_server_2:7001 false"
    depends_on:
      - kafka
      - connection_coordinator

  connection_coordinator:
      networks:
          my_network:
            ipv4_address: 172.20.0.8
      build:
        context: ./backend
      image: connection_coordinator
      container_name: connection_coordinator
      hostname: connection_coordinator
      ports:
        - "9999:9999"
      command: >
          mvn exec:java -Dexec.mainClass="com.server.ConnectionCoordinator"

  client_1:
    networks:
        my_network:
          ipv4_address: 172.20.0.20
    build:
      context: ./frontend
    image: client
    container_name: client_1
    ports:
      - "3000:3000"
    depends_on:
      - primary_server
      - connection_coordinator

  client_2:
    networks:
        my_network:
          ipv4_address: 172.20.0.21
    image: client
    container_name: client_2
    ports:
      - "3001:3000"
    depends_on:
      - primary_server
      - connection_coordinator
  
  client_3:
    networks:
        my_network:
          ipv4_address: 172.20.0.22
    image: client
    container_name: client_3
    ports:
      - "3002:3000"
    depends_on:
      - primary_server
      - connection_coordinator

  client_4:
    networks:
        my_network:
          ipv4_address: 172.20.0.23
    image: client
    container_name: client_4
    ports:
      - "3003:3000"
    depends_on:
      - primary_server
      - connection_coordinator

  