services:

  kafka:
    image: apache/kafka:latest # Official Confluent Kafka image
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # Add this line
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

  backup_server:
    build:
      context: ./backend
    image: server
    container_name: backup_server
    ports:
      - "8888:8888" # Expose port 8888 for client communication
      - "6001:6001" # Expose port 5002 for heartbeat communication
      - "6002:6002" # Expose port 5002 for Incremental Updates (otherServerHBPort + 1)
      - "6003:6003" # Expose port 5003 for Full game state updates (otherServerHBPort + 2)
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8888 6001 primary_server:5001 false"
    depends_on:
      - kafka

  primary_server:
    image: server
    container_name: primary_server
    ports:
      - "8887:8887" # Expose port 8887 for client communication
      - "5001:5001" # Expose port 5001 for heartbeat communication
      - "5002:5002" # Expose port 5002 for Incremental Updates (otherServerHBPort + 1)
      - "5003:5003" # Expose port 5003 for Full game state updates (otherServerHBPort + 2)
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -D"exec.mainClass"="com.server.WebServer" -D"exec.args"="8887 5001 backup_server:6001 true"
    depends_on:
      - backup_server # Guarantee startup order.

  client_1:
    build:
      context: ./frontend
    image: client
    container_name: client_1
    ports:
      - "3000:3000"
    depends_on:
      - primary_server

  client_2:
    image: client
    container_name: client_2
    ports:
      - "3001:3000"
    depends_on:
      - primary_server
