networks:
  my_overlay:
    driver: overlay

services:
  kafka:
    image: apache/kafka:latest
    networks:
      - my_overlay
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_LOG_RETENTION_HOURS: "1"
      KAFKA_LOG_CLEANUP_POLICY: "delete"
    deploy:
      placement:
        constraints: [node.role == manager]

  primary_server:
    image: server
    networks:
      - my_overlay
    ports:
      - "8887:8887"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8887 5001 backup_server_1:6001,backup_server_2:7001,backup_server_3:4001 true"
    deploy:
      placement:
        constraints: [node.role == manager]

  backup_server_1:
    image: server
    networks:
      - my_overlay
    ports:
      - "8888:8888"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8888 6001 primary_server:5001,backup_server_2:7001,backup_server_3:4001 false"

  backup_server_2:
    image: server
    networks:
      - my_overlay
    ports:
      - "8889:8889"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8889 7001 primary_server:5001,backup_server_1:6001,backup_server_3:4001 false"

  backup_server_3:
    image: server
    networks:
      - my_overlay
    ports:
      - "8890:8890"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8890 4001 primary_server:5001,backup_server_1:6001,backup_server_2:7001 false"

  connection_coordinator:
    image: connection_coordinator
    networks:
      - my_overlay
    ports:
      - "9999:9999"
    command: >
      mvn exec:java -Dexec.mainClass="com.server.ConnectionCoordinator"

  client:
    image: client
    networks:
      - my_overlay
    ports:
      - "3000:3000"
    deploy:
      replicas: 4
