version: '3.9'
services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "19092:19092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LOCAL:PLAINTEXT,REMOTE:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "LOCAL://0.0.0.0:9092,REMOTE://0.0.0.0:9093,CONTROLLER://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "LOCAL://127.0.0.1:9092,REMOTE://100.75.36.115:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "REMOTE"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:19092"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  connection_coordinator:
    network_mode: host
    image: connection_coordinator
    build:
      context: ./backend
    ports:
      - "9999:9999"
    environment:
      PRIMARY_SERVER_IP: 127.0.0.1
      COORDINATOR_IP: 127.0.0.1
    command: >
      sh -c "mvn exec:java -Dexec.mainClass='com.server.ConnectionCoordinator'"
  primary_server:
    network_mode: host
    image: server
    build:
      context: ./backend
    ports:
      - "8887:8887"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      TAILSCALE_IP: 127.0.0.1
      KAFKA_BOOTSTRAP_SERVERS: 127.0.0.1:9092
      BACKUP_SERVER_1_IP: 127.0.0.1
      BACKUP_SERVER_2_IP: 127.0.0.1
      BACKUP_SERVER_3_IP: 127.0.0.1
      PRIMARY_SERVER_IP: 127.0.0.1
      COORDINATOR_IP: 127.0.0.1
    command: >
      sh -c "/wait-for.sh 127.0.0.1:6001 127.0.0.1:7001 127.0.0.1:4001 -- mvn exec:java -Dexec.mainClass='com.server.WebServer' -Dexec.args='8887 5001 127.0.0.1:6001,127.0.0.1:7001,127.0.0.1:4001 true'"

  backup_server_1:
    network_mode: host
    image: server
    build:
      context: ./backend
    ports:
      - "8888:8888"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      TAILSCALE_IP: 127.0.0.1
      KAFKA_BOOTSTRAP_SERVERS: 127.0.0.1:9092
      COORDINATOR_IP: 127.0.0.1
      BACKUP_SERVER_1_IP: 127.0.0.1
      BACKUP_SERVER_2_IP: 127.0.0.1
      BACKUP_SERVER_3_IP: 127.0.0.1
      PRIMARY_SERVER_IP: 127.0.0.1
    command: >
      sh -c '/wait-for.sh 127.0.0.1:9092:9092 -- mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8888 6001 127.0.0.1:5001,127.0.0.1:7001,127.0.0.1:4001 false"'

  backup_server_2:
    network_mode: "host"
    image: server
    build:
      context: ./backend
    ports:
      - "8889:8889"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
    environment:
      TAILSCALE_IP: 127.0.0.1
      KAFKA_BOOTSTRAP_SERVERS: 127.0.0.1:9092
      COORDINATOR_IP: 127.0.0.1
      BACKUP_SERVER_1_IP: 127.0.0.1
      BACKUP_SERVER_2_IP: 127.0.0.1
      BACKUP_SERVER_3_IP: 127.0.0.1
      PRIMARY_SERVER_IP: 127.0.0.1
    command: >
      sh -c '/wait-for.sh 127.0.0.1:9092:9092 -- mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8889 7001 127.0.0.1:5001,127.0.0.1:6001,127.0.0.1:4001 false"'

  backup_server_3:
    network_mode: "host"
    image: server
    build:
      context: ./backend
    ports:
      - "8890:8890"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    environment:
      TAILSCALE_IP: 127.0.0.1
      KAFKA_BOOTSTRAP_SERVERS: 127.0.0.1:9092
      COORDINATOR_IP: 127.0.0.1
      BACKUP_SERVER_1_IP: 127.0.0.1
      BACKUP_SERVER_2_IP: 127.0.0.1
      BACKUP_SERVER_3_IP: 127.0.0.1
      PRIMARY_SERVER_IP: 127.0.0.1
    command: >
      sh -c '/wait-for.sh 127.0.0.1:9092:9092 -- mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8890 4001 127.0.0.1:5001,127.0.0.1:6001,127.0.0.1:7001 false"'

