volumes:
  kafka_data:
  tailscale-var-lib:

networks:
  my_network:
    driver: overlay
    attachable: true

services:
  kafka:
    image: bitnami/kafka:latest
    networks:
      - my_network
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://100.83.215.115:9092,CONTROLLER://100.83.215.115:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
      - "29092:29092"
    deploy:
      placement:
        constraints:
          - node.labels.role == jin

  connection_coordinator:
    image: connection_coordinator
    build:
      context: ./backend
    hostname: connection_coordinator
    ports:
      - "9999:9999"
    environment:
      PRIMARY_SERVER_IP: 100.83.215.115
      COORDINATOR_IP: 100.72.227.86
    command: >
      mvn exec:java -Dexec.mainClass="com.server.ConnectionCoordinator"
    networks:
      - my_network
    deploy:
      placement:
        constraints:
          - node.labels.role == sidd

  primary_server:
    image: server
    build:
      context: ./backend
    hostname: primary_server
    ports:
      - "8887:8887"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      TAILSCALE_IP: 100.83.215.115
      KAFKA_BOOTSTRAP_SERVERS: 100.83.215.115:9092
      BACKUP_SERVER_1_IP: 100.121.63.106
      BACKUP_SERVER_2_IP: 100.121.63.106
      BACKUP_SERVER_3_IP: 100.121.63.106
      PRIMARY_SERVER_IP: 100.83.215.115
      COORDINATOR_IP: 100.72.227.86
    command: >
      sh -c "/wait-for-backups.sh && mvn exec:java -Dexec.mainClass='com.server.WebServer' -Dexec.args='8887 5001 100.121.63.106:6001,100.121.63.106:7001,100.121.63.106:4001 true'"
    networks:
      - my_network
    deploy:
      placement:
        constraints:
          - node.labels.role == primary

  backup_server_1:
    image: server
    build:
      context: ./backend
    hostname: backup_server_1
    ports:
      - "8888:8888"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      TAILSCALE_IP: 100.121.63.106
      KAFKA_BOOTSTRAP_SERVERS: 100.83.215.115:9092
      COORDINATOR_IP: 100.72.227.86
      BACKUP_SERVER_1_IP: 100.121.63.106
      BACKUP_SERVER_2_IP: 100.121.63.106
      BACKUP_SERVER_3_IP: 100.121.63.106
      PRIMARY_SERVER_IP: 100.83.215.115
    command: >
      sh -c "/wait-for-kafka.sh && mvn exec:java -Dexec.mainClass='com.server.WebServer' -Dexec.args='8888 6001 100.83.215.115:5001,100.121.63.106:7001,100.121.63.106:4001 false'"
    networks:
      - my_network
    deploy:
      placement:
        constraints:
          - node.labels.role == mich

  backup_server_2:
    image: server
    build:
      context: ./backend
    hostname: backup_server_2
    ports:
      - "8889:8889"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
    environment:
      TAILSCALE_IP: 100.121.63.106
      KAFKA_BOOTSTRAP_SERVERS: 100.83.215.115:9092
      COORDINATOR_IP: 100.72.227.86
      BACKUP_SERVER_1_IP: 100.121.63.106
      BACKUP_SERVER_2_IP: 100.121.63.106
      BACKUP_SERVER_3_IP: 100.121.63.106
      PRIMARY_SERVER_IP: 100.83.215.115
    command: >
      sh -c "/wait-for-kafka.sh && mvn exec:java -Dexec.mainClass='com.server.WebServer' -Dexec.args='8889 7001 100.83.215.115:5001,100.121.63.106:6001,100.121.63.106:4001 false'"
    networks:
      - my_network
    deploy:
      placement:
        constraints:
          - node.labels.role == mich

  backup_server_3:
    image: server
    build:
      context: ./backend
    hostname: backup_server_3
    ports:
      - "8890:8890"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    environment:
      TAILSCALE_IP: 100.121.63.106
      KAFKA_BOOTSTRAP_SERVERS: 100.83.215.115:9092
      COORDINATOR_IP: 100.72.227.86
      BACKUP_SERVER_1_IP: 100.121.63.106
      BACKUP_SERVER_2_IP: 100.121.63.106
      BACKUP_SERVER_3_IP: 100.121.63.106
      PRIMARY_SERVER_IP: 100.83.215.115
    command: >
      sh -c "/wait-for-kafka.sh && mvn exec:java -Dexec.mainClass='com.server.WebServer' -Dexec.args='8890 4001 100.83.215.115:5001,100.121.63.106:6001,100.121.63.106:7001 false'"
    networks:
      - my_network
    deploy:
      placement:
        constraints:
          - node.labels.role == mich
