services:
  connection_coordinator:
    build:
      context: ./backend  # Path to Dockerfile directory
    container_name: connection_coordinator
    ports:
      - "9999:9999"
    command: >
      mvn exec:java -Dexec.mainClass="com.server.ConnectionCoordinator"
    restart: unless-stopped