services:
  primary_server:
    build:
      context: ../backend
    image: server
    container_name: backup_server_1
    ports:
      - "8888:8888"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 52.205.162.73:9092
      CURRENT_SERVER: 18.233.245.244
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer"
      -Dexec.args="8888 6001 18.233.245.244:6001, false"