services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "19092:19092"
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LOCAL:PLAINTEXT,REMOTE:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "LOCAL://0.0.0.0:9092,REMOTE://0.0.0.0:9093,CONTROLLER://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "LOCAL://127.0.0.1:9092,REMOTE://${KAFKA_TAILSCALE_IP}:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "REMOTE"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:19092"
    extra_hosts:
      - "host.docker.internal:host-gateway"
