services:
  primary_server:
    image: server
    build:
      context: ../backend
    ports:
      - "8887:8887"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
    environment:
      TAILSCALE_IP: 127.0.0.1
      KAFKA_BOOTSTRAP_SERVERS: 100.75.36.115:9092
      BACKUP_SERVER_1_IP: 127.0.0.1
      BACKUP_SERVER_2_IP: 127.0.0.1
      BACKUP_SERVER_3_IP: 100.85.115.122
      PRIMARY_SERVER_IP: 127.0.0.1
      COORDINATOR_IP: 127.0.0.1
    command: >
      sh -c mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8887 5001 127.0.0.1:6001,127.0.0.1:7001,100.85.115.122:4001 true"
