services:
  connection_coordinator:
    image: connection_coordinator
    build:
      context: ../backend
    ports:
      - "9999:9999"
    environment:
      PRIMARY_SERVER_IP: 127.0.0.1
      COORDINATOR_IP: 127.0.0.1
    command: >
      mvn exec:java -Dexec.mainClass="com.server.ConnectionCoordinator"