services:
  backup_server_1:
    network_mode: host
    image: server
    build:
      context: ../backend
    ports:
      - "8888:8888"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
    environment:
      TAILSCALE_IP: 127.0.0.1
      KAFKA_BOOTSTRAP_SERVERS: 100.75.36.115:9092
      COORDINATOR_IP: 127.0.0.1
      BACKUP_SERVER_1_IP: 127.0.0.1
      BACKUP_SERVER_2_IP: 127.0.0.1
      BACKUP_SERVER_3_IP: 100.85.115.122
      PRIMARY_SERVER_IP: 127.0.0.1
    command: >
      mvn exec:java -Dexec.mainClass="com.server.WebServer" -Dexec.args="8888 6001 127.0.0.1:5001,127.0.0.1:7001,100.85.115.122:4001 false"
